/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as RegisterRouteImport } from "./routes/register";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as AuthedRouteImport } from "./routes/_authed";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AuthedStudioRouteImport } from "./routes/_authed/studio";
import { Route as AuthedProjectRouteImport } from "./routes/_authed/project";
import { Route as AuthedOrganizationRouteImport } from "./routes/_authed/organization";
import { Route as AuthedDigitalWorkerRouteImport } from "./routes/_authed/digital-worker";
import { Route as AuthedStudioIndexRouteImport } from "./routes/_authed/studio.index";
import { Route as AuthedProjectIndexRouteImport } from "./routes/_authed/project.index";
import { Route as AuthedOrganizationIndexRouteImport } from "./routes/_authed/organization.index";
import { Route as AuthedDigitalWorkerIndexRouteImport } from "./routes/_authed/digital-worker.index";
import { Route as AuthedStudioSetupRouteImport } from "./routes/_authed/studio.setup";
import { Route as AuthedStudioEditableRouteImport } from "./routes/_authed/studio.editable";
import { Route as AuthedStudioCreatedRouteImport } from "./routes/_authed/studio.created";
import { Route as AuthedStudioAllRouteImport } from "./routes/_authed/studio.all";
import { Route as AuthedProjectProjectIdRouteImport } from "./routes/_authed/project.$projectId";
import { Route as AuthedOrganizationProjectsRouteImport } from "./routes/_authed/organization.projects";
import { Route as AuthedOrganizationMembersRouteImport } from "./routes/_authed/organization.members";
import { Route as AuthedDigitalWorkerAgentIdRouteImport } from "./routes/_authed/digital-worker.$agentId";
import { Route as AuthedProjectProjectIdIndexRouteImport } from "./routes/_authed/project.$projectId.index";
import { Route as AuthedDigitalWorkerAgentIdIndexRouteImport } from "./routes/_authed/digital-worker.$agentId.index";
import { Route as AuthedStudioAgentIdSetupRouteImport } from "./routes/_authed/studio.$agentId.setup";
import { Route as AuthedProjectProjectIdTeamRouteImport } from "./routes/_authed/project.$projectId.team";
import { Route as AuthedProjectProjectIdSandboxRouteImport } from "./routes/_authed/project.$projectId.sandbox";
import { Route as AuthedProjectProjectIdKnowledgeTagsRouteImport } from "./routes/_authed/project.$projectId.knowledge-tags";
import { Route as AuthedProjectProjectIdKnowledgeRouteImport } from "./routes/_authed/project.$projectId.knowledge";
import { Route as AuthedProjectProjectIdExperienceRouteImport } from "./routes/_authed/project.$projectId.experience";
import { Route as AuthedProjectProjectIdDeliverableRouteImport } from "./routes/_authed/project.$projectId.deliverable";
import { Route as AuthedDigitalWorkerAgentIdCollaborationRouteImport } from "./routes/_authed/digital-worker.$agentId.collaboration";
import { Route as AuthedProjectProjectIdTeamIndexRouteImport } from "./routes/_authed/project.$projectId.team.index";
import { Route as AuthedProjectProjectIdKnowledgeIndexRouteImport } from "./routes/_authed/project.$projectId.knowledge.index";
import { Route as AuthedProjectProjectIdExperienceIndexRouteImport } from "./routes/_authed/project.$projectId.experience.index";
import { Route as AuthedProjectProjectIdDeliverableIndexRouteImport } from "./routes/_authed/project.$projectId.deliverable.index";
import { Route as AuthedDigitalWorkerAgentIdCollaborationIndexRouteImport } from "./routes/_authed/digital-worker.$agentId.collaboration.index";
import { Route as AuthedProjectProjectIdTeamOperatorsRouteImport } from "./routes/_authed/project.$projectId.team.operators";
import { Route as AuthedProjectProjectIdTeamDigitalWorkersRouteImport } from "./routes/_authed/project.$projectId.team.digital-workers";
import { Route as AuthedProjectProjectIdKnowledgeAssetIdRouteImport } from "./routes/_authed/project.$projectId.knowledge.$assetId";
import { Route as AuthedProjectProjectIdExperienceAssetIdRouteImport } from "./routes/_authed/project.$projectId.experience.$assetId";
import { Route as AuthedProjectProjectIdDeliverableAssetIdRouteImport } from "./routes/_authed/project.$projectId.deliverable.$assetId";
import { Route as AuthedDigitalWorkerAgentIdCollaborationConversationIdRouteImport } from "./routes/_authed/digital-worker.$agentId.collaboration.$conversationId";

const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedRoute = AuthedRouteImport.update({
  id: "/_authed",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedStudioRoute = AuthedStudioRouteImport.update({
  id: "/studio",
  path: "/studio",
  getParentRoute: () => AuthedRoute,
} as any);
const AuthedProjectRoute = AuthedProjectRouteImport.update({
  id: "/project",
  path: "/project",
  getParentRoute: () => AuthedRoute,
} as any);
const AuthedOrganizationRoute = AuthedOrganizationRouteImport.update({
  id: "/organization",
  path: "/organization",
  getParentRoute: () => AuthedRoute,
} as any);
const AuthedDigitalWorkerRoute = AuthedDigitalWorkerRouteImport.update({
  id: "/digital-worker",
  path: "/digital-worker",
  getParentRoute: () => AuthedRoute,
} as any);
const AuthedStudioIndexRoute = AuthedStudioIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthedStudioRoute,
} as any);
const AuthedProjectIndexRoute = AuthedProjectIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthedProjectRoute,
} as any);
const AuthedOrganizationIndexRoute = AuthedOrganizationIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthedOrganizationRoute,
} as any);
const AuthedDigitalWorkerIndexRoute =
  AuthedDigitalWorkerIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthedDigitalWorkerRoute,
  } as any);
const AuthedStudioSetupRoute = AuthedStudioSetupRouteImport.update({
  id: "/setup",
  path: "/setup",
  getParentRoute: () => AuthedStudioRoute,
} as any);
const AuthedStudioEditableRoute = AuthedStudioEditableRouteImport.update({
  id: "/editable",
  path: "/editable",
  getParentRoute: () => AuthedStudioRoute,
} as any);
const AuthedStudioCreatedRoute = AuthedStudioCreatedRouteImport.update({
  id: "/created",
  path: "/created",
  getParentRoute: () => AuthedStudioRoute,
} as any);
const AuthedStudioAllRoute = AuthedStudioAllRouteImport.update({
  id: "/all",
  path: "/all",
  getParentRoute: () => AuthedStudioRoute,
} as any);
const AuthedProjectProjectIdRoute = AuthedProjectProjectIdRouteImport.update({
  id: "/$projectId",
  path: "/$projectId",
  getParentRoute: () => AuthedProjectRoute,
} as any);
const AuthedOrganizationProjectsRoute =
  AuthedOrganizationProjectsRouteImport.update({
    id: "/projects",
    path: "/projects",
    getParentRoute: () => AuthedOrganizationRoute,
  } as any);
const AuthedOrganizationMembersRoute =
  AuthedOrganizationMembersRouteImport.update({
    id: "/members",
    path: "/members",
    getParentRoute: () => AuthedOrganizationRoute,
  } as any);
const AuthedDigitalWorkerAgentIdRoute =
  AuthedDigitalWorkerAgentIdRouteImport.update({
    id: "/$agentId",
    path: "/$agentId",
    getParentRoute: () => AuthedDigitalWorkerRoute,
  } as any);
const AuthedProjectProjectIdIndexRoute =
  AuthedProjectProjectIdIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthedProjectProjectIdRoute,
  } as any);
const AuthedDigitalWorkerAgentIdIndexRoute =
  AuthedDigitalWorkerAgentIdIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthedDigitalWorkerAgentIdRoute,
  } as any);
const AuthedStudioAgentIdSetupRoute =
  AuthedStudioAgentIdSetupRouteImport.update({
    id: "/$agentId/setup",
    path: "/$agentId/setup",
    getParentRoute: () => AuthedStudioRoute,
  } as any);
const AuthedProjectProjectIdTeamRoute =
  AuthedProjectProjectIdTeamRouteImport.update({
    id: "/team",
    path: "/team",
    getParentRoute: () => AuthedProjectProjectIdRoute,
  } as any);
const AuthedProjectProjectIdSandboxRoute =
  AuthedProjectProjectIdSandboxRouteImport.update({
    id: "/sandbox",
    path: "/sandbox",
    getParentRoute: () => AuthedProjectProjectIdRoute,
  } as any);
const AuthedProjectProjectIdKnowledgeTagsRoute =
  AuthedProjectProjectIdKnowledgeTagsRouteImport.update({
    id: "/knowledge-tags",
    path: "/knowledge-tags",
    getParentRoute: () => AuthedProjectProjectIdRoute,
  } as any);
const AuthedProjectProjectIdKnowledgeRoute =
  AuthedProjectProjectIdKnowledgeRouteImport.update({
    id: "/knowledge",
    path: "/knowledge",
    getParentRoute: () => AuthedProjectProjectIdRoute,
  } as any);
const AuthedProjectProjectIdExperienceRoute =
  AuthedProjectProjectIdExperienceRouteImport.update({
    id: "/experience",
    path: "/experience",
    getParentRoute: () => AuthedProjectProjectIdRoute,
  } as any);
const AuthedProjectProjectIdDeliverableRoute =
  AuthedProjectProjectIdDeliverableRouteImport.update({
    id: "/deliverable",
    path: "/deliverable",
    getParentRoute: () => AuthedProjectProjectIdRoute,
  } as any);
const AuthedDigitalWorkerAgentIdCollaborationRoute =
  AuthedDigitalWorkerAgentIdCollaborationRouteImport.update({
    id: "/collaboration",
    path: "/collaboration",
    getParentRoute: () => AuthedDigitalWorkerAgentIdRoute,
  } as any);
const AuthedProjectProjectIdTeamIndexRoute =
  AuthedProjectProjectIdTeamIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthedProjectProjectIdTeamRoute,
  } as any);
const AuthedProjectProjectIdKnowledgeIndexRoute =
  AuthedProjectProjectIdKnowledgeIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthedProjectProjectIdKnowledgeRoute,
  } as any);
const AuthedProjectProjectIdExperienceIndexRoute =
  AuthedProjectProjectIdExperienceIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthedProjectProjectIdExperienceRoute,
  } as any);
const AuthedProjectProjectIdDeliverableIndexRoute =
  AuthedProjectProjectIdDeliverableIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthedProjectProjectIdDeliverableRoute,
  } as any);
const AuthedDigitalWorkerAgentIdCollaborationIndexRoute =
  AuthedDigitalWorkerAgentIdCollaborationIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthedDigitalWorkerAgentIdCollaborationRoute,
  } as any);
const AuthedProjectProjectIdTeamOperatorsRoute =
  AuthedProjectProjectIdTeamOperatorsRouteImport.update({
    id: "/operators",
    path: "/operators",
    getParentRoute: () => AuthedProjectProjectIdTeamRoute,
  } as any);
const AuthedProjectProjectIdTeamDigitalWorkersRoute =
  AuthedProjectProjectIdTeamDigitalWorkersRouteImport.update({
    id: "/digital-workers",
    path: "/digital-workers",
    getParentRoute: () => AuthedProjectProjectIdTeamRoute,
  } as any);
const AuthedProjectProjectIdKnowledgeAssetIdRoute =
  AuthedProjectProjectIdKnowledgeAssetIdRouteImport.update({
    id: "/$assetId",
    path: "/$assetId",
    getParentRoute: () => AuthedProjectProjectIdKnowledgeRoute,
  } as any);
const AuthedProjectProjectIdExperienceAssetIdRoute =
  AuthedProjectProjectIdExperienceAssetIdRouteImport.update({
    id: "/$assetId",
    path: "/$assetId",
    getParentRoute: () => AuthedProjectProjectIdExperienceRoute,
  } as any);
const AuthedProjectProjectIdDeliverableAssetIdRoute =
  AuthedProjectProjectIdDeliverableAssetIdRouteImport.update({
    id: "/$assetId",
    path: "/$assetId",
    getParentRoute: () => AuthedProjectProjectIdDeliverableRoute,
  } as any);
const AuthedDigitalWorkerAgentIdCollaborationConversationIdRoute =
  AuthedDigitalWorkerAgentIdCollaborationConversationIdRouteImport.update({
    id: "/$conversationId",
    path: "/$conversationId",
    getParentRoute: () => AuthedDigitalWorkerAgentIdCollaborationRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/digital-worker": typeof AuthedDigitalWorkerRouteWithChildren;
  "/organization": typeof AuthedOrganizationRouteWithChildren;
  "/project": typeof AuthedProjectRouteWithChildren;
  "/studio": typeof AuthedStudioRouteWithChildren;
  "/digital-worker/$agentId": typeof AuthedDigitalWorkerAgentIdRouteWithChildren;
  "/organization/members": typeof AuthedOrganizationMembersRoute;
  "/organization/projects": typeof AuthedOrganizationProjectsRoute;
  "/project/$projectId": typeof AuthedProjectProjectIdRouteWithChildren;
  "/studio/all": typeof AuthedStudioAllRoute;
  "/studio/created": typeof AuthedStudioCreatedRoute;
  "/studio/editable": typeof AuthedStudioEditableRoute;
  "/studio/setup": typeof AuthedStudioSetupRoute;
  "/digital-worker/": typeof AuthedDigitalWorkerIndexRoute;
  "/organization/": typeof AuthedOrganizationIndexRoute;
  "/project/": typeof AuthedProjectIndexRoute;
  "/studio/": typeof AuthedStudioIndexRoute;
  "/digital-worker/$agentId/collaboration": typeof AuthedDigitalWorkerAgentIdCollaborationRouteWithChildren;
  "/project/$projectId/deliverable": typeof AuthedProjectProjectIdDeliverableRouteWithChildren;
  "/project/$projectId/experience": typeof AuthedProjectProjectIdExperienceRouteWithChildren;
  "/project/$projectId/knowledge": typeof AuthedProjectProjectIdKnowledgeRouteWithChildren;
  "/project/$projectId/knowledge-tags": typeof AuthedProjectProjectIdKnowledgeTagsRoute;
  "/project/$projectId/sandbox": typeof AuthedProjectProjectIdSandboxRoute;
  "/project/$projectId/team": typeof AuthedProjectProjectIdTeamRouteWithChildren;
  "/studio/$agentId/setup": typeof AuthedStudioAgentIdSetupRoute;
  "/digital-worker/$agentId/": typeof AuthedDigitalWorkerAgentIdIndexRoute;
  "/project/$projectId/": typeof AuthedProjectProjectIdIndexRoute;
  "/digital-worker/$agentId/collaboration/$conversationId": typeof AuthedDigitalWorkerAgentIdCollaborationConversationIdRoute;
  "/project/$projectId/deliverable/$assetId": typeof AuthedProjectProjectIdDeliverableAssetIdRoute;
  "/project/$projectId/experience/$assetId": typeof AuthedProjectProjectIdExperienceAssetIdRoute;
  "/project/$projectId/knowledge/$assetId": typeof AuthedProjectProjectIdKnowledgeAssetIdRoute;
  "/project/$projectId/team/digital-workers": typeof AuthedProjectProjectIdTeamDigitalWorkersRoute;
  "/project/$projectId/team/operators": typeof AuthedProjectProjectIdTeamOperatorsRoute;
  "/digital-worker/$agentId/collaboration/": typeof AuthedDigitalWorkerAgentIdCollaborationIndexRoute;
  "/project/$projectId/deliverable/": typeof AuthedProjectProjectIdDeliverableIndexRoute;
  "/project/$projectId/experience/": typeof AuthedProjectProjectIdExperienceIndexRoute;
  "/project/$projectId/knowledge/": typeof AuthedProjectProjectIdKnowledgeIndexRoute;
  "/project/$projectId/team/": typeof AuthedProjectProjectIdTeamIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/organization/members": typeof AuthedOrganizationMembersRoute;
  "/organization/projects": typeof AuthedOrganizationProjectsRoute;
  "/studio/all": typeof AuthedStudioAllRoute;
  "/studio/created": typeof AuthedStudioCreatedRoute;
  "/studio/editable": typeof AuthedStudioEditableRoute;
  "/studio/setup": typeof AuthedStudioSetupRoute;
  "/digital-worker": typeof AuthedDigitalWorkerIndexRoute;
  "/organization": typeof AuthedOrganizationIndexRoute;
  "/project": typeof AuthedProjectIndexRoute;
  "/studio": typeof AuthedStudioIndexRoute;
  "/project/$projectId/knowledge-tags": typeof AuthedProjectProjectIdKnowledgeTagsRoute;
  "/project/$projectId/sandbox": typeof AuthedProjectProjectIdSandboxRoute;
  "/studio/$agentId/setup": typeof AuthedStudioAgentIdSetupRoute;
  "/digital-worker/$agentId": typeof AuthedDigitalWorkerAgentIdIndexRoute;
  "/project/$projectId": typeof AuthedProjectProjectIdIndexRoute;
  "/digital-worker/$agentId/collaboration/$conversationId": typeof AuthedDigitalWorkerAgentIdCollaborationConversationIdRoute;
  "/project/$projectId/deliverable/$assetId": typeof AuthedProjectProjectIdDeliverableAssetIdRoute;
  "/project/$projectId/experience/$assetId": typeof AuthedProjectProjectIdExperienceAssetIdRoute;
  "/project/$projectId/knowledge/$assetId": typeof AuthedProjectProjectIdKnowledgeAssetIdRoute;
  "/project/$projectId/team/digital-workers": typeof AuthedProjectProjectIdTeamDigitalWorkersRoute;
  "/project/$projectId/team/operators": typeof AuthedProjectProjectIdTeamOperatorsRoute;
  "/digital-worker/$agentId/collaboration": typeof AuthedDigitalWorkerAgentIdCollaborationIndexRoute;
  "/project/$projectId/deliverable": typeof AuthedProjectProjectIdDeliverableIndexRoute;
  "/project/$projectId/experience": typeof AuthedProjectProjectIdExperienceIndexRoute;
  "/project/$projectId/knowledge": typeof AuthedProjectProjectIdKnowledgeIndexRoute;
  "/project/$projectId/team": typeof AuthedProjectProjectIdTeamIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_authed": typeof AuthedRouteWithChildren;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/_authed/digital-worker": typeof AuthedDigitalWorkerRouteWithChildren;
  "/_authed/organization": typeof AuthedOrganizationRouteWithChildren;
  "/_authed/project": typeof AuthedProjectRouteWithChildren;
  "/_authed/studio": typeof AuthedStudioRouteWithChildren;
  "/_authed/digital-worker/$agentId": typeof AuthedDigitalWorkerAgentIdRouteWithChildren;
  "/_authed/organization/members": typeof AuthedOrganizationMembersRoute;
  "/_authed/organization/projects": typeof AuthedOrganizationProjectsRoute;
  "/_authed/project/$projectId": typeof AuthedProjectProjectIdRouteWithChildren;
  "/_authed/studio/all": typeof AuthedStudioAllRoute;
  "/_authed/studio/created": typeof AuthedStudioCreatedRoute;
  "/_authed/studio/editable": typeof AuthedStudioEditableRoute;
  "/_authed/studio/setup": typeof AuthedStudioSetupRoute;
  "/_authed/digital-worker/": typeof AuthedDigitalWorkerIndexRoute;
  "/_authed/organization/": typeof AuthedOrganizationIndexRoute;
  "/_authed/project/": typeof AuthedProjectIndexRoute;
  "/_authed/studio/": typeof AuthedStudioIndexRoute;
  "/_authed/digital-worker/$agentId/collaboration": typeof AuthedDigitalWorkerAgentIdCollaborationRouteWithChildren;
  "/_authed/project/$projectId/deliverable": typeof AuthedProjectProjectIdDeliverableRouteWithChildren;
  "/_authed/project/$projectId/experience": typeof AuthedProjectProjectIdExperienceRouteWithChildren;
  "/_authed/project/$projectId/knowledge": typeof AuthedProjectProjectIdKnowledgeRouteWithChildren;
  "/_authed/project/$projectId/knowledge-tags": typeof AuthedProjectProjectIdKnowledgeTagsRoute;
  "/_authed/project/$projectId/sandbox": typeof AuthedProjectProjectIdSandboxRoute;
  "/_authed/project/$projectId/team": typeof AuthedProjectProjectIdTeamRouteWithChildren;
  "/_authed/studio/$agentId/setup": typeof AuthedStudioAgentIdSetupRoute;
  "/_authed/digital-worker/$agentId/": typeof AuthedDigitalWorkerAgentIdIndexRoute;
  "/_authed/project/$projectId/": typeof AuthedProjectProjectIdIndexRoute;
  "/_authed/digital-worker/$agentId/collaboration/$conversationId": typeof AuthedDigitalWorkerAgentIdCollaborationConversationIdRoute;
  "/_authed/project/$projectId/deliverable/$assetId": typeof AuthedProjectProjectIdDeliverableAssetIdRoute;
  "/_authed/project/$projectId/experience/$assetId": typeof AuthedProjectProjectIdExperienceAssetIdRoute;
  "/_authed/project/$projectId/knowledge/$assetId": typeof AuthedProjectProjectIdKnowledgeAssetIdRoute;
  "/_authed/project/$projectId/team/digital-workers": typeof AuthedProjectProjectIdTeamDigitalWorkersRoute;
  "/_authed/project/$projectId/team/operators": typeof AuthedProjectProjectIdTeamOperatorsRoute;
  "/_authed/digital-worker/$agentId/collaboration/": typeof AuthedDigitalWorkerAgentIdCollaborationIndexRoute;
  "/_authed/project/$projectId/deliverable/": typeof AuthedProjectProjectIdDeliverableIndexRoute;
  "/_authed/project/$projectId/experience/": typeof AuthedProjectProjectIdExperienceIndexRoute;
  "/_authed/project/$projectId/knowledge/": typeof AuthedProjectProjectIdKnowledgeIndexRoute;
  "/_authed/project/$projectId/team/": typeof AuthedProjectProjectIdTeamIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/login"
    | "/register"
    | "/digital-worker"
    | "/organization"
    | "/project"
    | "/studio"
    | "/digital-worker/$agentId"
    | "/organization/members"
    | "/organization/projects"
    | "/project/$projectId"
    | "/studio/all"
    | "/studio/created"
    | "/studio/editable"
    | "/studio/setup"
    | "/digital-worker/"
    | "/organization/"
    | "/project/"
    | "/studio/"
    | "/digital-worker/$agentId/collaboration"
    | "/project/$projectId/deliverable"
    | "/project/$projectId/experience"
    | "/project/$projectId/knowledge"
    | "/project/$projectId/knowledge-tags"
    | "/project/$projectId/sandbox"
    | "/project/$projectId/team"
    | "/studio/$agentId/setup"
    | "/digital-worker/$agentId/"
    | "/project/$projectId/"
    | "/digital-worker/$agentId/collaboration/$conversationId"
    | "/project/$projectId/deliverable/$assetId"
    | "/project/$projectId/experience/$assetId"
    | "/project/$projectId/knowledge/$assetId"
    | "/project/$projectId/team/digital-workers"
    | "/project/$projectId/team/operators"
    | "/digital-worker/$agentId/collaboration/"
    | "/project/$projectId/deliverable/"
    | "/project/$projectId/experience/"
    | "/project/$projectId/knowledge/"
    | "/project/$projectId/team/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/login"
    | "/register"
    | "/organization/members"
    | "/organization/projects"
    | "/studio/all"
    | "/studio/created"
    | "/studio/editable"
    | "/studio/setup"
    | "/digital-worker"
    | "/organization"
    | "/project"
    | "/studio"
    | "/project/$projectId/knowledge-tags"
    | "/project/$projectId/sandbox"
    | "/studio/$agentId/setup"
    | "/digital-worker/$agentId"
    | "/project/$projectId"
    | "/digital-worker/$agentId/collaboration/$conversationId"
    | "/project/$projectId/deliverable/$assetId"
    | "/project/$projectId/experience/$assetId"
    | "/project/$projectId/knowledge/$assetId"
    | "/project/$projectId/team/digital-workers"
    | "/project/$projectId/team/operators"
    | "/digital-worker/$agentId/collaboration"
    | "/project/$projectId/deliverable"
    | "/project/$projectId/experience"
    | "/project/$projectId/knowledge"
    | "/project/$projectId/team";
  id:
    | "__root__"
    | "/"
    | "/_authed"
    | "/login"
    | "/register"
    | "/_authed/digital-worker"
    | "/_authed/organization"
    | "/_authed/project"
    | "/_authed/studio"
    | "/_authed/digital-worker/$agentId"
    | "/_authed/organization/members"
    | "/_authed/organization/projects"
    | "/_authed/project/$projectId"
    | "/_authed/studio/all"
    | "/_authed/studio/created"
    | "/_authed/studio/editable"
    | "/_authed/studio/setup"
    | "/_authed/digital-worker/"
    | "/_authed/organization/"
    | "/_authed/project/"
    | "/_authed/studio/"
    | "/_authed/digital-worker/$agentId/collaboration"
    | "/_authed/project/$projectId/deliverable"
    | "/_authed/project/$projectId/experience"
    | "/_authed/project/$projectId/knowledge"
    | "/_authed/project/$projectId/knowledge-tags"
    | "/_authed/project/$projectId/sandbox"
    | "/_authed/project/$projectId/team"
    | "/_authed/studio/$agentId/setup"
    | "/_authed/digital-worker/$agentId/"
    | "/_authed/project/$projectId/"
    | "/_authed/digital-worker/$agentId/collaboration/$conversationId"
    | "/_authed/project/$projectId/deliverable/$assetId"
    | "/_authed/project/$projectId/experience/$assetId"
    | "/_authed/project/$projectId/knowledge/$assetId"
    | "/_authed/project/$projectId/team/digital-workers"
    | "/_authed/project/$projectId/team/operators"
    | "/_authed/digital-worker/$agentId/collaboration/"
    | "/_authed/project/$projectId/deliverable/"
    | "/_authed/project/$projectId/experience/"
    | "/_authed/project/$projectId/knowledge/"
    | "/_authed/project/$projectId/team/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthedRoute: typeof AuthedRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  RegisterRoute: typeof RegisterRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/register": {
      id: "/register";
      path: "/register";
      fullPath: "/register";
      preLoaderRoute: typeof RegisterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authed": {
      id: "/_authed";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authed/studio": {
      id: "/_authed/studio";
      path: "/studio";
      fullPath: "/studio";
      preLoaderRoute: typeof AuthedStudioRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/project": {
      id: "/_authed/project";
      path: "/project";
      fullPath: "/project";
      preLoaderRoute: typeof AuthedProjectRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/organization": {
      id: "/_authed/organization";
      path: "/organization";
      fullPath: "/organization";
      preLoaderRoute: typeof AuthedOrganizationRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/digital-worker": {
      id: "/_authed/digital-worker";
      path: "/digital-worker";
      fullPath: "/digital-worker";
      preLoaderRoute: typeof AuthedDigitalWorkerRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/studio/": {
      id: "/_authed/studio/";
      path: "/";
      fullPath: "/studio/";
      preLoaderRoute: typeof AuthedStudioIndexRouteImport;
      parentRoute: typeof AuthedStudioRoute;
    };
    "/_authed/project/": {
      id: "/_authed/project/";
      path: "/";
      fullPath: "/project/";
      preLoaderRoute: typeof AuthedProjectIndexRouteImport;
      parentRoute: typeof AuthedProjectRoute;
    };
    "/_authed/organization/": {
      id: "/_authed/organization/";
      path: "/";
      fullPath: "/organization/";
      preLoaderRoute: typeof AuthedOrganizationIndexRouteImport;
      parentRoute: typeof AuthedOrganizationRoute;
    };
    "/_authed/digital-worker/": {
      id: "/_authed/digital-worker/";
      path: "/";
      fullPath: "/digital-worker/";
      preLoaderRoute: typeof AuthedDigitalWorkerIndexRouteImport;
      parentRoute: typeof AuthedDigitalWorkerRoute;
    };
    "/_authed/studio/setup": {
      id: "/_authed/studio/setup";
      path: "/setup";
      fullPath: "/studio/setup";
      preLoaderRoute: typeof AuthedStudioSetupRouteImport;
      parentRoute: typeof AuthedStudioRoute;
    };
    "/_authed/studio/editable": {
      id: "/_authed/studio/editable";
      path: "/editable";
      fullPath: "/studio/editable";
      preLoaderRoute: typeof AuthedStudioEditableRouteImport;
      parentRoute: typeof AuthedStudioRoute;
    };
    "/_authed/studio/created": {
      id: "/_authed/studio/created";
      path: "/created";
      fullPath: "/studio/created";
      preLoaderRoute: typeof AuthedStudioCreatedRouteImport;
      parentRoute: typeof AuthedStudioRoute;
    };
    "/_authed/studio/all": {
      id: "/_authed/studio/all";
      path: "/all";
      fullPath: "/studio/all";
      preLoaderRoute: typeof AuthedStudioAllRouteImport;
      parentRoute: typeof AuthedStudioRoute;
    };
    "/_authed/project/$projectId": {
      id: "/_authed/project/$projectId";
      path: "/$projectId";
      fullPath: "/project/$projectId";
      preLoaderRoute: typeof AuthedProjectProjectIdRouteImport;
      parentRoute: typeof AuthedProjectRoute;
    };
    "/_authed/organization/projects": {
      id: "/_authed/organization/projects";
      path: "/projects";
      fullPath: "/organization/projects";
      preLoaderRoute: typeof AuthedOrganizationProjectsRouteImport;
      parentRoute: typeof AuthedOrganizationRoute;
    };
    "/_authed/organization/members": {
      id: "/_authed/organization/members";
      path: "/members";
      fullPath: "/organization/members";
      preLoaderRoute: typeof AuthedOrganizationMembersRouteImport;
      parentRoute: typeof AuthedOrganizationRoute;
    };
    "/_authed/digital-worker/$agentId": {
      id: "/_authed/digital-worker/$agentId";
      path: "/$agentId";
      fullPath: "/digital-worker/$agentId";
      preLoaderRoute: typeof AuthedDigitalWorkerAgentIdRouteImport;
      parentRoute: typeof AuthedDigitalWorkerRoute;
    };
    "/_authed/project/$projectId/": {
      id: "/_authed/project/$projectId/";
      path: "/";
      fullPath: "/project/$projectId/";
      preLoaderRoute: typeof AuthedProjectProjectIdIndexRouteImport;
      parentRoute: typeof AuthedProjectProjectIdRoute;
    };
    "/_authed/digital-worker/$agentId/": {
      id: "/_authed/digital-worker/$agentId/";
      path: "/";
      fullPath: "/digital-worker/$agentId/";
      preLoaderRoute: typeof AuthedDigitalWorkerAgentIdIndexRouteImport;
      parentRoute: typeof AuthedDigitalWorkerAgentIdRoute;
    };
    "/_authed/studio/$agentId/setup": {
      id: "/_authed/studio/$agentId/setup";
      path: "/$agentId/setup";
      fullPath: "/studio/$agentId/setup";
      preLoaderRoute: typeof AuthedStudioAgentIdSetupRouteImport;
      parentRoute: typeof AuthedStudioRoute;
    };
    "/_authed/project/$projectId/team": {
      id: "/_authed/project/$projectId/team";
      path: "/team";
      fullPath: "/project/$projectId/team";
      preLoaderRoute: typeof AuthedProjectProjectIdTeamRouteImport;
      parentRoute: typeof AuthedProjectProjectIdRoute;
    };
    "/_authed/project/$projectId/sandbox": {
      id: "/_authed/project/$projectId/sandbox";
      path: "/sandbox";
      fullPath: "/project/$projectId/sandbox";
      preLoaderRoute: typeof AuthedProjectProjectIdSandboxRouteImport;
      parentRoute: typeof AuthedProjectProjectIdRoute;
    };
    "/_authed/project/$projectId/knowledge-tags": {
      id: "/_authed/project/$projectId/knowledge-tags";
      path: "/knowledge-tags";
      fullPath: "/project/$projectId/knowledge-tags";
      preLoaderRoute: typeof AuthedProjectProjectIdKnowledgeTagsRouteImport;
      parentRoute: typeof AuthedProjectProjectIdRoute;
    };
    "/_authed/project/$projectId/knowledge": {
      id: "/_authed/project/$projectId/knowledge";
      path: "/knowledge";
      fullPath: "/project/$projectId/knowledge";
      preLoaderRoute: typeof AuthedProjectProjectIdKnowledgeRouteImport;
      parentRoute: typeof AuthedProjectProjectIdRoute;
    };
    "/_authed/project/$projectId/experience": {
      id: "/_authed/project/$projectId/experience";
      path: "/experience";
      fullPath: "/project/$projectId/experience";
      preLoaderRoute: typeof AuthedProjectProjectIdExperienceRouteImport;
      parentRoute: typeof AuthedProjectProjectIdRoute;
    };
    "/_authed/project/$projectId/deliverable": {
      id: "/_authed/project/$projectId/deliverable";
      path: "/deliverable";
      fullPath: "/project/$projectId/deliverable";
      preLoaderRoute: typeof AuthedProjectProjectIdDeliverableRouteImport;
      parentRoute: typeof AuthedProjectProjectIdRoute;
    };
    "/_authed/digital-worker/$agentId/collaboration": {
      id: "/_authed/digital-worker/$agentId/collaboration";
      path: "/collaboration";
      fullPath: "/digital-worker/$agentId/collaboration";
      preLoaderRoute: typeof AuthedDigitalWorkerAgentIdCollaborationRouteImport;
      parentRoute: typeof AuthedDigitalWorkerAgentIdRoute;
    };
    "/_authed/project/$projectId/team/": {
      id: "/_authed/project/$projectId/team/";
      path: "/";
      fullPath: "/project/$projectId/team/";
      preLoaderRoute: typeof AuthedProjectProjectIdTeamIndexRouteImport;
      parentRoute: typeof AuthedProjectProjectIdTeamRoute;
    };
    "/_authed/project/$projectId/knowledge/": {
      id: "/_authed/project/$projectId/knowledge/";
      path: "/";
      fullPath: "/project/$projectId/knowledge/";
      preLoaderRoute: typeof AuthedProjectProjectIdKnowledgeIndexRouteImport;
      parentRoute: typeof AuthedProjectProjectIdKnowledgeRoute;
    };
    "/_authed/project/$projectId/experience/": {
      id: "/_authed/project/$projectId/experience/";
      path: "/";
      fullPath: "/project/$projectId/experience/";
      preLoaderRoute: typeof AuthedProjectProjectIdExperienceIndexRouteImport;
      parentRoute: typeof AuthedProjectProjectIdExperienceRoute;
    };
    "/_authed/project/$projectId/deliverable/": {
      id: "/_authed/project/$projectId/deliverable/";
      path: "/";
      fullPath: "/project/$projectId/deliverable/";
      preLoaderRoute: typeof AuthedProjectProjectIdDeliverableIndexRouteImport;
      parentRoute: typeof AuthedProjectProjectIdDeliverableRoute;
    };
    "/_authed/digital-worker/$agentId/collaboration/": {
      id: "/_authed/digital-worker/$agentId/collaboration/";
      path: "/";
      fullPath: "/digital-worker/$agentId/collaboration/";
      preLoaderRoute: typeof AuthedDigitalWorkerAgentIdCollaborationIndexRouteImport;
      parentRoute: typeof AuthedDigitalWorkerAgentIdCollaborationRoute;
    };
    "/_authed/project/$projectId/team/operators": {
      id: "/_authed/project/$projectId/team/operators";
      path: "/operators";
      fullPath: "/project/$projectId/team/operators";
      preLoaderRoute: typeof AuthedProjectProjectIdTeamOperatorsRouteImport;
      parentRoute: typeof AuthedProjectProjectIdTeamRoute;
    };
    "/_authed/project/$projectId/team/digital-workers": {
      id: "/_authed/project/$projectId/team/digital-workers";
      path: "/digital-workers";
      fullPath: "/project/$projectId/team/digital-workers";
      preLoaderRoute: typeof AuthedProjectProjectIdTeamDigitalWorkersRouteImport;
      parentRoute: typeof AuthedProjectProjectIdTeamRoute;
    };
    "/_authed/project/$projectId/knowledge/$assetId": {
      id: "/_authed/project/$projectId/knowledge/$assetId";
      path: "/$assetId";
      fullPath: "/project/$projectId/knowledge/$assetId";
      preLoaderRoute: typeof AuthedProjectProjectIdKnowledgeAssetIdRouteImport;
      parentRoute: typeof AuthedProjectProjectIdKnowledgeRoute;
    };
    "/_authed/project/$projectId/experience/$assetId": {
      id: "/_authed/project/$projectId/experience/$assetId";
      path: "/$assetId";
      fullPath: "/project/$projectId/experience/$assetId";
      preLoaderRoute: typeof AuthedProjectProjectIdExperienceAssetIdRouteImport;
      parentRoute: typeof AuthedProjectProjectIdExperienceRoute;
    };
    "/_authed/project/$projectId/deliverable/$assetId": {
      id: "/_authed/project/$projectId/deliverable/$assetId";
      path: "/$assetId";
      fullPath: "/project/$projectId/deliverable/$assetId";
      preLoaderRoute: typeof AuthedProjectProjectIdDeliverableAssetIdRouteImport;
      parentRoute: typeof AuthedProjectProjectIdDeliverableRoute;
    };
    "/_authed/digital-worker/$agentId/collaboration/$conversationId": {
      id: "/_authed/digital-worker/$agentId/collaboration/$conversationId";
      path: "/$conversationId";
      fullPath: "/digital-worker/$agentId/collaboration/$conversationId";
      preLoaderRoute: typeof AuthedDigitalWorkerAgentIdCollaborationConversationIdRouteImport;
      parentRoute: typeof AuthedDigitalWorkerAgentIdCollaborationRoute;
    };
  }
}

interface AuthedDigitalWorkerAgentIdCollaborationRouteChildren {
  AuthedDigitalWorkerAgentIdCollaborationConversationIdRoute: typeof AuthedDigitalWorkerAgentIdCollaborationConversationIdRoute;
  AuthedDigitalWorkerAgentIdCollaborationIndexRoute: typeof AuthedDigitalWorkerAgentIdCollaborationIndexRoute;
}

const AuthedDigitalWorkerAgentIdCollaborationRouteChildren: AuthedDigitalWorkerAgentIdCollaborationRouteChildren =
  {
    AuthedDigitalWorkerAgentIdCollaborationConversationIdRoute:
      AuthedDigitalWorkerAgentIdCollaborationConversationIdRoute,
    AuthedDigitalWorkerAgentIdCollaborationIndexRoute:
      AuthedDigitalWorkerAgentIdCollaborationIndexRoute,
  };

const AuthedDigitalWorkerAgentIdCollaborationRouteWithChildren =
  AuthedDigitalWorkerAgentIdCollaborationRoute._addFileChildren(
    AuthedDigitalWorkerAgentIdCollaborationRouteChildren,
  );

interface AuthedDigitalWorkerAgentIdRouteChildren {
  AuthedDigitalWorkerAgentIdCollaborationRoute: typeof AuthedDigitalWorkerAgentIdCollaborationRouteWithChildren;
  AuthedDigitalWorkerAgentIdIndexRoute: typeof AuthedDigitalWorkerAgentIdIndexRoute;
}

const AuthedDigitalWorkerAgentIdRouteChildren: AuthedDigitalWorkerAgentIdRouteChildren =
  {
    AuthedDigitalWorkerAgentIdCollaborationRoute:
      AuthedDigitalWorkerAgentIdCollaborationRouteWithChildren,
    AuthedDigitalWorkerAgentIdIndexRoute: AuthedDigitalWorkerAgentIdIndexRoute,
  };

const AuthedDigitalWorkerAgentIdRouteWithChildren =
  AuthedDigitalWorkerAgentIdRoute._addFileChildren(
    AuthedDigitalWorkerAgentIdRouteChildren,
  );

interface AuthedDigitalWorkerRouteChildren {
  AuthedDigitalWorkerAgentIdRoute: typeof AuthedDigitalWorkerAgentIdRouteWithChildren;
  AuthedDigitalWorkerIndexRoute: typeof AuthedDigitalWorkerIndexRoute;
}

const AuthedDigitalWorkerRouteChildren: AuthedDigitalWorkerRouteChildren = {
  AuthedDigitalWorkerAgentIdRoute: AuthedDigitalWorkerAgentIdRouteWithChildren,
  AuthedDigitalWorkerIndexRoute: AuthedDigitalWorkerIndexRoute,
};

const AuthedDigitalWorkerRouteWithChildren =
  AuthedDigitalWorkerRoute._addFileChildren(AuthedDigitalWorkerRouteChildren);

interface AuthedOrganizationRouteChildren {
  AuthedOrganizationMembersRoute: typeof AuthedOrganizationMembersRoute;
  AuthedOrganizationProjectsRoute: typeof AuthedOrganizationProjectsRoute;
  AuthedOrganizationIndexRoute: typeof AuthedOrganizationIndexRoute;
}

const AuthedOrganizationRouteChildren: AuthedOrganizationRouteChildren = {
  AuthedOrganizationMembersRoute: AuthedOrganizationMembersRoute,
  AuthedOrganizationProjectsRoute: AuthedOrganizationProjectsRoute,
  AuthedOrganizationIndexRoute: AuthedOrganizationIndexRoute,
};

const AuthedOrganizationRouteWithChildren =
  AuthedOrganizationRoute._addFileChildren(AuthedOrganizationRouteChildren);

interface AuthedProjectProjectIdDeliverableRouteChildren {
  AuthedProjectProjectIdDeliverableAssetIdRoute: typeof AuthedProjectProjectIdDeliverableAssetIdRoute;
  AuthedProjectProjectIdDeliverableIndexRoute: typeof AuthedProjectProjectIdDeliverableIndexRoute;
}

const AuthedProjectProjectIdDeliverableRouteChildren: AuthedProjectProjectIdDeliverableRouteChildren =
  {
    AuthedProjectProjectIdDeliverableAssetIdRoute:
      AuthedProjectProjectIdDeliverableAssetIdRoute,
    AuthedProjectProjectIdDeliverableIndexRoute:
      AuthedProjectProjectIdDeliverableIndexRoute,
  };

const AuthedProjectProjectIdDeliverableRouteWithChildren =
  AuthedProjectProjectIdDeliverableRoute._addFileChildren(
    AuthedProjectProjectIdDeliverableRouteChildren,
  );

interface AuthedProjectProjectIdExperienceRouteChildren {
  AuthedProjectProjectIdExperienceAssetIdRoute: typeof AuthedProjectProjectIdExperienceAssetIdRoute;
  AuthedProjectProjectIdExperienceIndexRoute: typeof AuthedProjectProjectIdExperienceIndexRoute;
}

const AuthedProjectProjectIdExperienceRouteChildren: AuthedProjectProjectIdExperienceRouteChildren =
  {
    AuthedProjectProjectIdExperienceAssetIdRoute:
      AuthedProjectProjectIdExperienceAssetIdRoute,
    AuthedProjectProjectIdExperienceIndexRoute:
      AuthedProjectProjectIdExperienceIndexRoute,
  };

const AuthedProjectProjectIdExperienceRouteWithChildren =
  AuthedProjectProjectIdExperienceRoute._addFileChildren(
    AuthedProjectProjectIdExperienceRouteChildren,
  );

interface AuthedProjectProjectIdKnowledgeRouteChildren {
  AuthedProjectProjectIdKnowledgeAssetIdRoute: typeof AuthedProjectProjectIdKnowledgeAssetIdRoute;
  AuthedProjectProjectIdKnowledgeIndexRoute: typeof AuthedProjectProjectIdKnowledgeIndexRoute;
}

const AuthedProjectProjectIdKnowledgeRouteChildren: AuthedProjectProjectIdKnowledgeRouteChildren =
  {
    AuthedProjectProjectIdKnowledgeAssetIdRoute:
      AuthedProjectProjectIdKnowledgeAssetIdRoute,
    AuthedProjectProjectIdKnowledgeIndexRoute:
      AuthedProjectProjectIdKnowledgeIndexRoute,
  };

const AuthedProjectProjectIdKnowledgeRouteWithChildren =
  AuthedProjectProjectIdKnowledgeRoute._addFileChildren(
    AuthedProjectProjectIdKnowledgeRouteChildren,
  );

interface AuthedProjectProjectIdTeamRouteChildren {
  AuthedProjectProjectIdTeamDigitalWorkersRoute: typeof AuthedProjectProjectIdTeamDigitalWorkersRoute;
  AuthedProjectProjectIdTeamOperatorsRoute: typeof AuthedProjectProjectIdTeamOperatorsRoute;
  AuthedProjectProjectIdTeamIndexRoute: typeof AuthedProjectProjectIdTeamIndexRoute;
}

const AuthedProjectProjectIdTeamRouteChildren: AuthedProjectProjectIdTeamRouteChildren =
  {
    AuthedProjectProjectIdTeamDigitalWorkersRoute:
      AuthedProjectProjectIdTeamDigitalWorkersRoute,
    AuthedProjectProjectIdTeamOperatorsRoute:
      AuthedProjectProjectIdTeamOperatorsRoute,
    AuthedProjectProjectIdTeamIndexRoute: AuthedProjectProjectIdTeamIndexRoute,
  };

const AuthedProjectProjectIdTeamRouteWithChildren =
  AuthedProjectProjectIdTeamRoute._addFileChildren(
    AuthedProjectProjectIdTeamRouteChildren,
  );

interface AuthedProjectProjectIdRouteChildren {
  AuthedProjectProjectIdDeliverableRoute: typeof AuthedProjectProjectIdDeliverableRouteWithChildren;
  AuthedProjectProjectIdExperienceRoute: typeof AuthedProjectProjectIdExperienceRouteWithChildren;
  AuthedProjectProjectIdKnowledgeRoute: typeof AuthedProjectProjectIdKnowledgeRouteWithChildren;
  AuthedProjectProjectIdKnowledgeTagsRoute: typeof AuthedProjectProjectIdKnowledgeTagsRoute;
  AuthedProjectProjectIdSandboxRoute: typeof AuthedProjectProjectIdSandboxRoute;
  AuthedProjectProjectIdTeamRoute: typeof AuthedProjectProjectIdTeamRouteWithChildren;
  AuthedProjectProjectIdIndexRoute: typeof AuthedProjectProjectIdIndexRoute;
}

const AuthedProjectProjectIdRouteChildren: AuthedProjectProjectIdRouteChildren =
  {
    AuthedProjectProjectIdDeliverableRoute:
      AuthedProjectProjectIdDeliverableRouteWithChildren,
    AuthedProjectProjectIdExperienceRoute:
      AuthedProjectProjectIdExperienceRouteWithChildren,
    AuthedProjectProjectIdKnowledgeRoute:
      AuthedProjectProjectIdKnowledgeRouteWithChildren,
    AuthedProjectProjectIdKnowledgeTagsRoute:
      AuthedProjectProjectIdKnowledgeTagsRoute,
    AuthedProjectProjectIdSandboxRoute: AuthedProjectProjectIdSandboxRoute,
    AuthedProjectProjectIdTeamRoute:
      AuthedProjectProjectIdTeamRouteWithChildren,
    AuthedProjectProjectIdIndexRoute: AuthedProjectProjectIdIndexRoute,
  };

const AuthedProjectProjectIdRouteWithChildren =
  AuthedProjectProjectIdRoute._addFileChildren(
    AuthedProjectProjectIdRouteChildren,
  );

interface AuthedProjectRouteChildren {
  AuthedProjectProjectIdRoute: typeof AuthedProjectProjectIdRouteWithChildren;
  AuthedProjectIndexRoute: typeof AuthedProjectIndexRoute;
}

const AuthedProjectRouteChildren: AuthedProjectRouteChildren = {
  AuthedProjectProjectIdRoute: AuthedProjectProjectIdRouteWithChildren,
  AuthedProjectIndexRoute: AuthedProjectIndexRoute,
};

const AuthedProjectRouteWithChildren = AuthedProjectRoute._addFileChildren(
  AuthedProjectRouteChildren,
);

interface AuthedStudioRouteChildren {
  AuthedStudioAllRoute: typeof AuthedStudioAllRoute;
  AuthedStudioCreatedRoute: typeof AuthedStudioCreatedRoute;
  AuthedStudioEditableRoute: typeof AuthedStudioEditableRoute;
  AuthedStudioSetupRoute: typeof AuthedStudioSetupRoute;
  AuthedStudioIndexRoute: typeof AuthedStudioIndexRoute;
  AuthedStudioAgentIdSetupRoute: typeof AuthedStudioAgentIdSetupRoute;
}

const AuthedStudioRouteChildren: AuthedStudioRouteChildren = {
  AuthedStudioAllRoute: AuthedStudioAllRoute,
  AuthedStudioCreatedRoute: AuthedStudioCreatedRoute,
  AuthedStudioEditableRoute: AuthedStudioEditableRoute,
  AuthedStudioSetupRoute: AuthedStudioSetupRoute,
  AuthedStudioIndexRoute: AuthedStudioIndexRoute,
  AuthedStudioAgentIdSetupRoute: AuthedStudioAgentIdSetupRoute,
};

const AuthedStudioRouteWithChildren = AuthedStudioRoute._addFileChildren(
  AuthedStudioRouteChildren,
);

interface AuthedRouteChildren {
  AuthedDigitalWorkerRoute: typeof AuthedDigitalWorkerRouteWithChildren;
  AuthedOrganizationRoute: typeof AuthedOrganizationRouteWithChildren;
  AuthedProjectRoute: typeof AuthedProjectRouteWithChildren;
  AuthedStudioRoute: typeof AuthedStudioRouteWithChildren;
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDigitalWorkerRoute: AuthedDigitalWorkerRouteWithChildren,
  AuthedOrganizationRoute: AuthedOrganizationRouteWithChildren,
  AuthedProjectRoute: AuthedProjectRouteWithChildren,
  AuthedStudioRoute: AuthedStudioRouteWithChildren,
};

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
